#!/usr/bin/env node
/**
 * Pulls brand assets straight from the app repo on GitHub.
 *
 * The Mozz mark and the Plex / Jellyfin / Navidrome logos are all owned by
 * thatcube/Mozz, not by this site. Copying them in by hand means the copies
 * silently rot the next time the artwork changes, so they are fetched from the
 * default branch and this script is the only way they get into the tree.
 *
 *   npm run brand
 *
 * Assets land in two places on purpose:
 *   public/    — served as files (favicon, apple-touch-icon, OG art)
 *   src/brand/ — inlined by components with Vite's `?raw`, which survives the
 *                bundle. Reading from public/ at render time does not, because
 *                the build runs from a different directory than the source.
 */
import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const RAW = 'https://raw.githubusercontent.com/thatcube/Mozz/main';
const BRANDS = 'Sources/MozzApp/Resources/Brands.xcassets';

const MARK = 'docs/brand/mozz_logo.svg';

const SERVERS = [
  { slug: 'plex', from: `${BRANDS}/PlexLogo.imageset/plex-logo.svg` },
  { slug: 'jellyfin', from: `${BRANDS}/JellyfinLogo.imageset/jellyfin-logo.svg` },
  { slug: 'navidrome', from: `${BRANDS}/NavidromeLogo.imageset/navidrome-logo.svg` },
];

async function get(path) {
  const url = `${RAW}/${path}`;
  const res = await fetch(url);
  if (!res.ok) throw new Error(`${res.status} ${res.statusText} fetching ${url}`);
  const body = await res.text();
  if (!body.includes('<svg')) throw new Error(`not an SVG: ${url}`);
  return body;
}

/**
 * The mark's favicon rendition. A browser tab draws it at 16px, where the
 * shaded body turns to mud — so every red collapses to one brand red.
 */
function flattenMark(svg) {
  return svg.replace(/fill="(#[0-9A-Fa-f]{6})"/g, (_m, hex) => {
    const n = parseInt(hex.slice(1), 16);
    const [r, g, b] = [(n >> 16) & 0xff, (n >> 8) & 0xff, n & 0xff];
    return r < 95 && g < 70 && b < 70 ? 'fill="#3E0606"' : 'fill="#C80028"';
  });
}

/**
 * Third-party logos ship with their own hard-coded fills, or none at all, which
 * means black. Each variant tints them to sit inside its own world, so the
 * fills are stripped and the artwork inherits `currentColor` instead.
 */
function normaliseServerLogo(svg) {
  const viewBox = (svg.match(/viewBox="([^"]+)"/) || [, '0 0 24 24'])[1];
  const inner = svg
    .replace(/<\?xml[^>]*\?>/g, '')
    .replace(/<!DOCTYPE[\s\S]*?>/g, '')
    .replace(/<metadata>[\s\S]*?<\/metadata>/g, '')
    .replace(/<title>[\s\S]*?<\/title>/g, '')
    .replace(/<svg[^>]*>/, '')
    .replace(/<\/svg>\s*$/, '')
    .replace(/\s(fill|stroke)="(?!none)[^"]*"/g, '')
    .replace(/\s+/g, ' ')
    .trim();
  return { viewBox, inner };
}

mkdirSync(join(root, 'public'), { recursive: true });
mkdirSync(join(root, 'src/brand'), { recursive: true });

const mark = await get(MARK);
writeFileSync(join(root, 'src/brand/mozz-logo.svg'), mark);
writeFileSync(join(root, 'public/logo.svg'), mark);
writeFileSync(join(root, 'public/favicon.svg'), flattenMark(mark));
console.log(
  `mark            ${String(mark.length).padStart(6)} bytes  → src/brand/mozz-logo.svg, public/logo.svg, public/favicon.svg`,
);

const entries = [];
for (const s of SERVERS) {
  const raw = await get(s.from);
  const { viewBox, inner } = normaliseServerLogo(raw);
  entries.push(
    `  ${s.slug}: {\n` +
      `    viewBox: ${JSON.stringify(viewBox)},\n` +
      `    inner: ${JSON.stringify(inner)},\n` +
      `  },`,
  );
  console.log(`${s.slug.padEnd(15)} ${String(raw.length).padStart(6)} bytes  → src/brand/servers.ts`);
}

writeFileSync(
  join(root, 'src/brand/servers.ts'),
  '// Generated by tools/sync-brand.mjs from thatcube/Mozz. Do not edit by hand.\n' +
    '// Fills are stripped so each variant can tint the logo with currentColor.\n\n' +
    'export interface ServerLogoArt {\n  viewBox: string;\n  inner: string;\n}\n\n' +
    `export const SERVER_LOGOS: Record<string, ServerLogoArt> = {\n${entries.join('\n')}\n};\n`,
);
